const api1 = require('./api1');
const login = require('./login');
const newcustomer = require('./files/Customer/newcustomer');
const deletecustomer = require('./files/Customer/deletecustomer');
const viewcustomer = require ('./files/Customer/viewcustomer');
const updatecustomer = require('./files/Customer/updatecustomer');
const insertdaily = require('./files/Maintanace/insertdailyshift');
const AddVehicle = require('./files/Transport/AddVehicle');
const deletevehicle = require('./files/Transport/deletevehicle');
const update= require('./files/Transport/update');
const edittranspoort= require('./files/Transport/edit');
const AddEmp = require('./files/Employee/AddEmp');
const DeleteEmp = require('./files/Employee/DeleteEmp');
const EditEmp = require('./files/Employee/EditEmp');
const Attendance = require('./files/Employee/Attendance');
const work = require('./files/Employee/work');
const addstockdetails = require ('./files/Restaurent/addstockdetails');
const deletestockdetails = require ('./files/Restaurent/deletedetails');
const tablebooking = require ('./files/Restaurent/tablebooking');
const tablebookingdelete = require ('./files/Restaurent/tablebookingdelete');
const deletedailyshift = require ('./files/Maintanace/deletedailyshift');
const add = require('./files/Accounts/add');
const view = require ('./files/Accounts/view');
const updateacc = require('./files/Accounts/update');
const deleteAcc = require('./files/Accounts/delete');
const insertequipment = require('./files/Maintanace/insertequipment');
const addbooking = require('./files/Customer/booking');
const deleteBooking = require ('./files/Customer/deletebooking');
const addstocks = require ('./files/Inventory/addstocks');
const deletestocks = require ('./files/Inventory/deletestock');
const viewcustomerbooking = require ('./files/Customer/viewcustomerbooking');
const UpdateEmp = require('./files/Employee/UpdateEmp');
const ViewEmp = require('./files/Employee/ViewEmp');
const updatedailyshift = require('./files/Maintanace/updatedailyshift');
const updateequipment = require('./files/Maintanace/updateequipment');
const deleteequipment = require('./files/Maintanace/deleteequipment');
const viewdailyshift = require('./files/Maintanace/viewdailyshift');
const viewequipment = require('./files/Maintanace/viewequipment');
const viewresstockdetails = require ('./files/Restaurent/viewresstockdetails');
const updateresstockdetails = require ('./files/Restaurent/updateresstockdetails');
const viewrestable = require ('./files/Restaurent/viewrestable');
const updaterestable = require ('./files/Restaurent/updaterestable');
const viewstockres2details = require('./files/Restaurent/viewstockres2details');
const viewTablePlan = require('./files/Restaurent/viewtableplan');
const viewtransport= require('./files/Transport/viewtransport');
const viewstock = require ('./files/Inventory/viewstock');
const updatestock = require('./files/Inventory/updatestock');
const addsupplier = require('./files/Inventory/addsupplier');
const viewsupplier = require('./files/Inventory/viewsup');
const updatesupplier = require('./files/Inventory/updatesupplier');
const deletesupplier = require('./files/Inventory/deletesupplier');
var express = require('express');

const app = express();
api1(app);
login(app);
newcustomer(app);
deletecustomer(app);
viewcustomer(app);
viewcustomerbooking(app);
updatecustomer(app);
insertdaily(app);
AddVehicle(app);
deletevehicle(app);
update(app);
edittranspoort(app);
AddEmp(app);
DeleteEmp(app);
EditEmp(app);
Attendance(app);
addstockdetails(app);
deletestockdetails(app);
tablebooking(app);
tablebookingdelete(app);
work(app);
deletedailyshift(app);
add(app);
view(app);
deleteAcc(app);
insertequipment(app);
addbooking(app);
deleteBooking(app);
addstocks(app);
deletestocks(app);
UpdateEmp(app);
ViewEmp(app);
updatedailyshift(app);
updateequipment(app);
deleteequipment(app);
viewdailyshift(app);
viewequipment(app);
viewresstockdetails(app);
updateresstockdetails(app);
viewrestable(app);
updaterestable(app);
viewstockres2details(app);
updateacc(app);
viewTablePlan(app);
viewtransport(app);
viewstock(app);
updatestock(app);
addsupplier(app);
viewsupplier(app);
updatesupplier(app);
deletesupplier(app);

app.listen(3000);
